{
 "title": "Finsight / UserLogin",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(finsight_users_successful_logins_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful Finsight Logins / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (tenant, loginType) (rate(finsight_users_successful_logins_count{loginType=\"finsight\", namespace=\"$namespace\"}[5m]) * 60)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Failed Finsight Logins / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (tenant, loginType) (rate(finsight_users_failed_logins_count{loginType=\"finsight\", namespace=\"$namespace\"}[5m]) * 60)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Successful SSO Logins / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (tenant, loginType) (rate(finsight_users_successful_logins_count{loginType=\"sso\", namespace=\"$namespace\"}[5m]) * 60)",
     "legendFormat": "sso login"
    }
   ]
  },
  {
   "title": "Failed SSO Logins / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (tenant, loginType) (rate(finsight_users_failed_logins_count{loginType=\"sso\", namespace=\"$namespace\"}[5m]) * 60)",
     "legendFormat": "sso login"
    }
   ]
  }
 ]
}