{
 "title": "Kubernetes / OOM&Fails",
 "tags": [
  "finsight",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Process in Container Oom Kill Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_oom_events_total - container_oom_events_total offset 5m)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container Oom Kill Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n(kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 5m >= 1)\n * ignoring(reason) kube_pod_container_status_last_terminated_reason{reason=~\"OOMKilled\"}\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container Failed Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n(kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 5m >= 0)\n * ignoring(reason) kube_pod_container_status_last_terminated_reason{reason=\"Error\"}\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}